export const GET_ORDER_NUMBER = "GET_ORDER_NUMBER";
export const UPDATE_ORDER_NUMBER = "UPDATE_ORDER_NUMBER";
export const HIDE_ORDER_MODAL = "HIDE_ORDER_MODAL";
export const SHOW_ORDER_MODAL = "SHOW_ORDER_MODAL";