export const USER_EDIT_FORM_SET_VALUE = 'USER_EDIT_FORM_SET_VALUE';
export const USER_EDIT_FORM_CHANGE_PASSWORD_VISION = 'USER_EDIT_FORM_CHANGE_PASSWORD_VISION';
export const CHANGE_ABLE_OF_EDIT_PASSWORD = "CHANGE_ABLE_OF_EDIT_PASSWORD";
export const CHANGE_ABLE_OF_EDIT_NAME = "CHANGE_ABLE_OF_EDIT_NAME";
export const CHANGE_ABLE_OF_EDIT_EMAIL = "CHANGE_ABLE_OF_EDIT_EMAIL";
export const LOAD_USER_DATA = 'LOAD_USER_DATA';
export const RESET_USER_DATA = 'RESET_USER_DATA';
export const CHANGE_ABLE_OF_INPUTS = "CHANGE_ABLE_OF_INPUTS";

export const setUserEditFormValue = (field, value) => ({
  type: USER_EDIT_FORM_SET_VALUE,
  field,
  value
})

