export const WS_CONNECTION_PROFILE_START = 'WS_CONNECTION_START';
export const WS_CONNECTION_PROFILE_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_PROFILE_ERROR = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_PROFILE_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_GET_ORDER_PROFILE = 'WS_GET_ORDER';
export const WS_SEND_ORDER_PROFILE = 'WS_SEND_ORDER';

export const wsActionsProfile = {
  wsInit: WS_CONNECTION_PROFILE_START,
  // wsClose: WS_CONNECTION_CLOSED,
  wsSendOrder: WS_SEND_ORDER_PROFILE,
  onOpen: WS_CONNECTION_PROFILE_SUCCESS,
  onClose: WS_CONNECTION_PROFILE_CLOSED,
  onError: WS_CONNECTION_PROFILE_ERROR,
  onMessage: WS_GET_ORDER_PROFILE,
}